package characters.job;

public enum JobType {

	GUERRIERO, LADRO, MONACO, MAGO_NERO, MAGO_BIANCO, MAGO_ROSSO, MAGO_BLU, CAVALIERE_LUCE, CAVALIERE_TENEBRA, NINJA, RANGER, SCOLARO, GEOMANTE,
	INVOCATORE, BARDO, SAGGIO, DRAGONE, SAMURAI, BERSEKER, DOMATORE, BALLERINO, ALCHIMISTA, MIMO, PALADINO
}
